/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 20 22:00:38 GMT 2026
 */

package org.apache.commons.lang3;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.lang3.CharUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class CharUtils_ESTest extends CharUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String string0 = CharUtils.toString('\u0080');
      assertEquals("\u0080", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      char char0 = CharUtils.toChar("", 'X');
      assertEquals('X', char0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      boolean boolean0 = CharUtils.isOctal('7');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      boolean boolean0 = CharUtils.isOctal('0');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      boolean boolean0 = CharUtils.isHex('F');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      boolean boolean0 = CharUtils.isHex('A');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      boolean boolean0 = CharUtils.isHex('f');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      boolean boolean0 = CharUtils.isHex('a');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      boolean boolean0 = CharUtils.isAsciiPrintable('\u0090');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      boolean boolean0 = CharUtils.isAsciiPrintable(' ');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      int int0 = CharUtils.toIntValue('9', 1513);
      assertEquals(9, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      boolean boolean0 = CharUtils.isAsciiControl('\u008C');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      boolean boolean0 = CharUtils.isAsciiControl(' ');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      boolean boolean0 = CharUtils.isAsciiAlphaUpper('Z');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      boolean boolean0 = CharUtils.isAsciiAlpha('z');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      boolean boolean0 = CharUtils.isAsciiAlpha('a');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      boolean boolean0 = CharUtils.isAscii('\u0085');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Character character0 = CharUtils.toCharacterObject('I');
      assertEquals('I', (char)character0);
      
      int int0 = CharUtils.toIntValue(character0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Character character0 = CharUtils.toCharacterObject('5');
      assertEquals('5', (char)character0);
      
      int int0 = CharUtils.toIntValue(character0);
      assertEquals(5, int0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      int int0 = CharUtils.toIntValue('0');
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Character character0 = CharUtils.toCharacterObject(" N*sPxKFA{");
      assertEquals(' ', (char)character0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Character character0 = CharUtils.toCharacterObject("K0KzCz5Q*O?bDn");
      assertEquals('K', (char)character0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      char char0 = CharUtils.toChar("3zIk3fNx&$", '|');
      assertEquals('3', char0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      char char0 = CharUtils.toChar("'DWSu!Q`E$");
      assertEquals('\'', char0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      char char0 = CharUtils.toChar("0Z)~\"xb)b>F?jFzYe");
      assertEquals('0', char0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      char char0 = CharUtils.toChar("L");
      assertEquals('L', char0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      char char0 = CharUtils.toChar((Character) null, '9');
      assertEquals('9', char0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Character character0 = Character.valueOf('t');
      char char0 = CharUtils.toChar(character0, 'H');
      assertEquals('t', char0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Character character0 = Character.valueOf('6');
      char char0 = CharUtils.toChar(character0);
      assertEquals('6', char0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Character character0 = Character.valueOf('q');
      char char0 = CharUtils.toChar(character0);
      assertEquals('q', char0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      int int0 = CharUtils.compare('&', '&');
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      int int0 = CharUtils.compare('a', '6');
      assertEquals(43, int0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      // Undeclared exception!
      try { 
        CharUtils.toIntValue((Character) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // ch
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      // Undeclared exception!
      try { 
        CharUtils.toChar("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The String must not be empty
         //
         verifyException("org.apache.commons.lang3.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      // Undeclared exception!
      try { 
        CharUtils.toChar((Character) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // ch
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      int int0 = CharUtils.toIntValue('2');
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      // Undeclared exception!
      try { 
        CharUtils.toIntValue('L');
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The character L is not in the range '0' - '9'
         //
         verifyException("org.apache.commons.lang3.CharUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      boolean boolean0 = CharUtils.isAsciiNumeric('6');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      boolean boolean0 = CharUtils.isAsciiNumeric('a');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      boolean boolean0 = CharUtils.isAsciiNumeric(' ');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      boolean boolean0 = CharUtils.isAsciiAlphaUpper('z');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      boolean boolean0 = CharUtils.isAsciiAlphaUpper(' ');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      boolean boolean0 = CharUtils.isAsciiAlphaUpper('P');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      boolean boolean0 = CharUtils.isAsciiAlphaLower('\n');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      boolean boolean0 = CharUtils.isAsciiAlphaLower('c');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      boolean boolean0 = CharUtils.isAsciiAlphaLower('}');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      String string0 = CharUtils.unicodeEscaped('\u0000');
      assertEquals("\\u0000", string0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      CharUtils charUtils0 = new CharUtils();
      char char0 = CharUtils.toChar((Character) charUtils0.LF);
      assertEquals('\n', char0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      String string0 = CharUtils.unicodeEscaped((Character) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      String string0 = CharUtils.toString((Character) '\r');
      assertEquals("\r", string0);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      String string0 = CharUtils.toString((Character) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      String string0 = CharUtils.toString('C');
      assertEquals("C", string0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      String string0 = CharUtils.toString('\u008B');
      assertEquals("\u008B", string0);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Character character0 = Character.valueOf('d');
      int int0 = CharUtils.toIntValue(character0, 2147483639);
      assertEquals(2147483639, int0);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      int int0 = CharUtils.toIntValue((Character) null, 59);
      assertEquals(59, int0);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      int int0 = CharUtils.toIntValue('0', (int) '0');
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      int int0 = CharUtils.toIntValue('q', (-689));
      assertEquals((-689), int0);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      Character character0 = CharUtils.toCharacterObject("");
      int int0 = CharUtils.toIntValue(character0, (-412));
      assertEquals((-412), int0);
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      char char0 = CharUtils.toChar((String) null, '\r');
      assertEquals('\r', char0);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      CharUtils charUtils0 = new CharUtils();
      char char0 = CharUtils.toChar((Character) charUtils0.CR, ',');
      assertEquals('\r', char0);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      boolean boolean0 = CharUtils.isOctal('');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      boolean boolean0 = CharUtils.isOctal('\u0000');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      boolean boolean0 = CharUtils.isHex('\n');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      boolean boolean0 = CharUtils.isHex('');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      boolean boolean0 = CharUtils.isHex('8');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      boolean boolean0 = CharUtils.isAsciiPrintable('');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      boolean boolean0 = CharUtils.isAsciiPrintable('\u0000');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      // Undeclared exception!
      try { 
        CharUtils.toIntValue((Character) '\u0000');
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The character \u0000 is not in the range '0' - '9'
         //
         verifyException("org.apache.commons.lang3.CharUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      boolean boolean0 = CharUtils.isAsciiControl('');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      boolean boolean0 = CharUtils.isAsciiControl('\n');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      boolean boolean0 = CharUtils.isAsciiAlphanumeric('8');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      boolean boolean0 = CharUtils.isAsciiAlphanumeric('n');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      boolean boolean0 = CharUtils.isAsciiAlpha('2');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      boolean boolean0 = CharUtils.isAsciiAlphanumeric('\u0086');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      boolean boolean0 = CharUtils.isAsciiAlpha('A');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      boolean boolean0 = CharUtils.isAscii('s');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      boolean boolean0 = CharUtils.isAscii('\u0080');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      CharUtils charUtils0 = new CharUtils();
      String string0 = CharUtils.unicodeEscaped((Character) charUtils0.CR);
      assertEquals("\\u000d", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test78()  throws Throwable  {
      Character character0 = CharUtils.toCharacterObject('$');
      assertEquals('$', (char)character0);
  }

  @Test(timeout = 4000)
  public void test79()  throws Throwable  {
      // Undeclared exception!
      try { 
        CharUtils.toChar((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // The String must not be empty
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test80()  throws Throwable  {
      int int0 = CharUtils.compare('C', 'm');
      assertEquals((-42), int0);
  }

  @Test(timeout = 4000)
  public void test81()  throws Throwable  {
      Character character0 = CharUtils.toCharacterObject("0!FJW@:FWo*");
      assertNotNull(character0);
      assertEquals('0', (char)character0);
      
      int int0 = CharUtils.toIntValue(character0);
      assertEquals(0, int0);
  }
}
